import type { Metadata } from "next";
import "./globals.css";
import Nav from "./components/nav/nav";
import { StyledComponentsRegistry } from "./lib";
import { Public_Sans } from "next/font/google";
import { ChildrenContainer, Container, NavContainer } from "./page.styled";

const publicSans = Public_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={publicSans.className}>
        <StyledComponentsRegistry>
          <Container>
            <NavContainer>
              <Nav />
            </NavContainer>
            <ChildrenContainer>{children}</ChildrenContainer>
          </Container>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
