import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Nav from "./components/nav/nav";
import { StyledComponentsRegistry } from "./lib";

import { ChildrenContainer, Container, NavContainer } from "./page.styled";

const publicSans = localFont({
  src: "./assets/fonts/PublicSans-VariableFont_wght.ttf",
  variable: "--font-public-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${publicSans.variable} `}>
        <StyledComponentsRegistry>
          <Container>
            <NavContainer>
              <Nav />
            </NavContainer>
            <ChildrenContainer>{children}</ChildrenContainer>
          </Container>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
